default_platform(:android)

platform :android do

    desc "Submit a new Internal Build to Play Store"
    lane :internal do
    upload_to_play_store(
        track: 'internal',
#         release_status: 'draft',
        aab: 'app/build/outputs/bundle/devRelease/app-dev-release.aab'
    )
    end

    desc "Submit a new Beta build to Play Store"
    lane :alpha do
      upload_to_play_store(
        track: 'alpha',
        aab: 'app/build/outputs/bundle/devRelease/app-dev-release.aab'
      )
    end

    desc "Submit a new Beta build to Play Store"
    lane :beta do
      upload_to_play_store(
        track: 'beta',
        aab: 'app/build/outputs/bundle/masterRelease/app-master-release.aab'
      )
    end
#   В случае если мы хотим двигать сборки из одной стадии тестирования в другую
#   desc "Promote Internal to Alpha"
#   lane :promote_internal_to_alpha do
#     upload_to_play_store(track: 'internal', track_promote_to: 'alpha')
#   end
#
#   desc "Promote Alpha to Beta"
#   lane :promote_alpha_to_beta do
#     upload_to_play_store(track: 'alpha', track_promote_to: 'beta')
#   end

#   desc "Promote Beta to Production"
#   lane :promote_beta_to_production do
#     upload_to_play_store(track: 'beta', track_promote_to: 'production')
#   end
end
